int updateMusicSpeed();
int setMusicTrack(uint8_t number);
int playState_checkForCompletedRows();
int isPositionValid();
int playState_lockTetrimino();
int calculate_score_with_clockcycles_and_mods(uint8_t level, uint8_t completedLines, uint8_t* score, Modifications modification);
int rotate_tetrimino();
int update_level_with_clockcycles(int lines_cleared);
int playState_updateLinesAndStatistics_with_clockcycles_and_mods(Modifications modification);
int updatePlayfield();
int rotate_tetrimino();
int shift_tetrimino();
int drop_tetrimino();
int playState_playerControlsActiveTetrimino();
int drop_tetrimino();
int incrementPieceStat();
int generateNextPseudorandomNumber();
int playState_spawnNextTetrimino();
int chooseNextTetrimino();
int realStart();
int updateLineClearingAnimation();
int updatePaletteForLevel();
int twoDigsToPPU();
int copyPlayfieldRowToVRAM();
int demoButtonsTable_indexIncr();
int initPlayfieldIfTypeB();
int playState_bTypeGoalCheck();

int pollController_actualRead();
int pollControllerButtons();
int pollController();
